import { rice,arecanut,apple,ashgourd,banana,barley,beetroot,bittergourd,blackgram,blackpepper,bottlegourd,brinjal,cabbage,cardamom,carrot,cashewnuts,cauliflower,coffee,coriander,cotton,cucumber,drumstick,garlic,ginger,grapes,horsegram,jackfruit,jowar,jute,
    ladyfinger,maize,mango,moong,onion,orange,papaya,pineapple,pomegranate,potato,pumpkin,radish,ragi,rapeseed,ridgegourd,sesamum,
    soyabean,sunflower,sweetpotato,tapioca,tomato,turmeric,watermelon,wheat
} from "../../assets/crop_folder";
const crops=[
    {
        name:"Apple",
        icon:apple,
    },
    {
        name:"Arecanut",
        icon:arecanut,
    },
    {
        name:"Ashgourd",
        icon:ashgourd,
    },
    {
        name:"Banana",
        icon:banana,
    },
    {
        name:"Barley",
        icon:barley,
    },
    {
        name:"Beetroot",
        icon:beetroot,
    },
    {
        name:"Bittergourd",
        icon:bittergourd,
    },
    {
        name:"Blackgram",
        icon:blackgram,
    },
    {
        name:"Blackpepper",
        icon:blackpepper,
    },
    {
        name:"Bottlegourd",
        icon:bottlegourd,
    },
    {
        name:"Brinjal",
        icon:brinjal,
    },
    {
        name:"Cabbage",
        icon:cabbage,
    },
    {
        name:"Cardamom",
        icon:cardamom,
    },
    {
        name:"Carrot",
        icon:carrot,
    },
    {
        name:"Cashewnuts",
        icon:cashewnuts,
    },
    {
        name:"Cauliflower",
        icon:cauliflower,
    },
    {
        name:"Coffee",
        icon:coffee,
    },
    {
        name:"Coriander",
        icon:coriander,
    },
    {
        name:"Cotton",
        icon:cotton,
    },
    {
        name:"Cucumber",
        icon:cucumber,
    },
    {
        name:"Drumstick",
        icon:drumstick,
    },
    {
        name:"Garlic",
        icon:garlic,
    },
    {
        name:"Ginger",
        icon:ginger,
    },
    {
        name:"Grapes",
        icon:grapes,
    },
    {
        name:"HorseGram",
        icon:horsegram,
    },
    {
        name:"Jackfruit",
        icon:jackfruit,
    },
    {
        name:"Jowar",
        icon:jowar,
    },
    {
        name:"Jute",
        icon:jute,
    },
    {
        name:"Ladyfinger",
        icon:ladyfinger,
    },
    {
        name:"Maize",
        icon:maize,
    },
    {
        name:"Mango",
        icon:mango,
    },
    {
        name:"Moong",
        icon:moong,
    },
    {
        name:"Onion",
        icon:onion,
    },
    {
        name:"Orange",
        icon:orange,
    },
    {
        name:"Papaya",
        icon:papaya,
    },
    {
        name:"Pineapple",
        icon:pineapple,
    },
    {
        name:"Pomegranate",
        icon:pomegranate,
    },
    {
        name:"Potato",
        icon:potato,
    },
    {
        name:"Pumpkin",
        icon:pumpkin,
    },
    {
        name:"Radish",
        icon:radish,
    },
    {
        name:"Ragi",
        icon:ragi,
    },
    {
        name:"Rapeseed",
        icon:rapeseed,
    },
    {
        name:"Rice",
        icon:rice,
    },
    {
        name:"Ridgegourd",
        icon:ridgegourd,
    },
    {
        name:"Sesamum",
        icon:sesamum,
    },
    {
        name:"Soyabeen",
        icon:soyabean,
    },
    {
        name:"Sunflower",
        icon:sunflower,
    },
    {
        name:"Sweetpotato",
        icon:sweetpotato,
    },
    {
        name:"Tapioca",
        icon:tapioca,
    },
    {
        name:"Tomato",
        icon:tomato,
    },
    {
        name:"Turmeric",
        icon:turmeric,
    },
    {
        name:"Watermelon",
        icon:watermelon,
    },
    {
        name:"Wheat",
        icon:wheat,
    },
]
export {crops};